/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code_java;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author Tran Thang
 */
public class Sua extends javax.swing.JFrame {

    /**
     * Creates new form Sua
     */
    ketNoi kn = new ketNoi();
    Vector dsKhoa;
    String luu;
    
    boolean kiemtra(){
        String err="";
        if(txtSBD.getText().length()==0){
            err+="Bạn Phải nhập SBD!\n";
        }
        else{
            try {
                Long.parseLong(txtSBD.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số báo danh phải là dạng số");
            }
        }
        
        if(!txtSBD.getText().equals(luu)){
            if(traSBD()==true)
                err+="Bạn không thể sửa thành số báo danh này";
        }
        
        if(txtHoTen.getText().length()==0){
            err+="Bạn Phải nhập ho tên!\n";
        }
        
        if(txtNgaySinh.getText().length()==0){
            err+="Bạn Phải nhập ngay sinh!\n";
        }
        else{
            try {
            Date ns = Date.valueOf(txtNgaySinh.getText());
        } catch (Exception e) {
            err+="ngay sinh khong dung\n";
        }
        }
        if(txtToan.getText().length()==0){
            err+="Bạn Phải nhập điểm toán!\n";
        }
        else{
            try {
                Integer.parseInt(txtToan.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "điểm phải là dạng số");
            }
        }
        if(txtVan.getText().length()==0){
            err+="Bạn Phải nhập điểm văn!\n";
        }
        else{
            try {
                Integer.parseInt(txtVan.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "điểm phải là dạng số");
            }
        }
        if(txtAnh.getText().length()==0){
            err+="Bạn Phải nhập điểm anh!\n";
        }
        else{
            try {
                Integer.parseInt(txtAnh.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "điểm phải là dạng số");
            }
        }
        if(!err.equals("")){
            JOptionPane.showMessageDialog(this, err);
            return false;
        }
        return true;
    }
    
    boolean traSBD(){
        try {
            kn.ketNoi();
            String sql = "select SBD from hoSoSinhVien where SBD='"+txtSBD.getText()+"'";
            kn.stmt = kn.cnn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = kn.stmt.executeQuery(sql);
            if(rs.next()==true){
                return true;
            }
            kn.ngatketnoi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        return false;
    }
    
    private void LoadKhoa()
    {
        try
        {
            kn.ketNoi();
            String sql="select * from nganh";
            ResultSet rs = kn.stmt.executeQuery(sql);
            dsKhoa=new Vector();
            cbNganh.removeAllItems();      
            while(rs.next())
            {
                Object o1 = rs.getObject(1);//mada
                dsKhoa.addElement(o1);
                Object o2 = rs.getObject(1);//tenda
                cbNganh.addItem(o2);
            }
            kn.ngatketnoi();
        }
        catch(Exception ex)
        {
            System.out.println("Lỗi load dữ liệu: "+ ex.toString());
        }
    }
    public Sua(String[] dl) {
        initComponents();
        LoadKhoa();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        txtSBD.setText(dl[0]);
        luu=dl[0];
        txtHoTen.setText(dl[1]);
        if("false".equalsIgnoreCase(dl[2]))
            btNam.setSelected(true);
        else
            btNu.setSelected(true);
        txtNgaySinh.setText(dl[3].substring(0, 10));
        txtToan.setText(dl[5]);
        txtVan.setText(dl[6]);
        txtAnh.setText(dl[7]);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtToan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAnh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtSBD = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btNam = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btNu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVan = new javax.swing.JTextField();
        cbNganh = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Mã Ngành:");

        txtToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToanActionPerformed(evt);
            }
        });

        jLabel14.setText("Toán:");

        jLabel15.setText("Văn:");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Anh:");

        jButton2.setText("Nhập Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lưu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Số báo danh:");

        btNam.setText("Nam");
        btNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNamActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ và Tên:");

        btNu.setText("Nữ");

        jLabel9.setText("Giới tính:");

        jLabel10.setText("Ngày sinh:");

        cbNganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNam)
                                .addGap(18, 18, 18)
                                .addComponent(btNu))
                            .addComponent(txtSBD, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtHoTen)
                            .addComponent(txtNgaySinh)
                            .addComponent(cbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btNam)
                    .addComponent(btNu))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoat!");
        if(kq==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(kiemtra()==true){
            try
        {
            kn.ketNoi();
            String sql="update hoSoSinhVien set HoTen='"+txtHoTen.getText()
                    +"',GioiTinh='"+!btNam.isSelected()
                    +"', NgaySinh='"+txtNgaySinh.getText()
                    +"', MaNganh='"+dsKhoa.get(cbNganh.getSelectedIndex())+"' where SBD='"+txtSBD.getText()+"'";
            String sql1="update Diem set Toan='"+txtToan.getText()
                    +"',Van='"+txtVan.getText()
                    +"', Anh='"+txtAnh.getText()+"' where MaSo='"+txtSBD.getText()+"'";
            JOptionPane.showMessageDialog(this, "Đã lưu thông tin");
            kn.stmt.executeUpdate(sql);
            kn.stmt.executeUpdate(sql1);
            kn.ngatketnoi();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Lỗi sql1 "+ex.toString());
        }   
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new Sua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btNam;
    private javax.swing.JRadioButton btNu;
    private javax.swing.JComboBox cbNganh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAnh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSBD;
    private javax.swing.JTextField txtToan;
    private javax.swing.JTextField txtVan;
    // End of variables declaration//GEN-END:variables
}
